name: nlp
channels:
  - anaconda
  - conda-forge
  - pkgs/main
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.6
  - aiohttp=3.11.13
  - aiosignal=1.3.2
  - annotated-types=0.7.0
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=25.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - catalogue=2.0.10
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpathlib=0.20.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - confection=0.1.5
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cpython=3.11.11
  - cycler=0.12.1
  - cymem=2.0.11
  - cyrus-sasl=2.1.28
  - cython-blis=1.0.1
  - datasets=3.3.2
  - dbus=1.13.18
  - debugpy=1.8.12
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - filelock=3.17.0
  - fmt=11.0.2
  - fontconfig=2.14.1
  - fonttools=4.56.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gensim=4.3.3
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - huggingface_hub=0.29.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - langcodes=3.4.1
  - language-data=1.3.0
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libiconv=1.18
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libmamba=2.0.7
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libtorch=2.4.1
  - libuuid=1.41.5
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.41
  - libzlib=1.2.13
  - llvm-openmp=20.1.2
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - mamba=2.0.7
  - marisa-trie=1.2.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.3
  - mistune=3.1.2
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - murmurhash=1.0.10
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - nltk=3.9.1
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.89.1
  - numba=0.59.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.1
  - orc=2.0.1
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - polars=1.24.0
  - preshed=3.0.9
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - propcache=0.2.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyparsing=3.2.1
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytorch=2.4.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtshadertools=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebengine=6.7.2
  - qtwebsockets=6.7.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.23.1
  - s2n=1.3.27
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - send2trash=1.8.3
  - setuptools=72.1.0
  - shellingham=1.5.4
  - simdjson=3.12.2
  - six=1.16.0
  - sleef=3.8
  - smart-open=7.1.0
  - smart_open=7.1.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - spacy-model-es_core_news_md=3.8.0
  - spdlog=1.15.1
  - sqlite=3.45.3
  - srsly=2.5.1
  - stack_data=0.6.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - terminado=0.18.1
  - thinc=8.3.2
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tokenizers=0.21.1
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - ujson=5.10.0
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wasabi=1.1.3
  - wcwidth=0.2.13
  - weasel=0.4.1
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.43
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6

